### ISSUE TITLE
Dedicated Domain For Sustain Care

### ISSUE THREAD

**Issue by prestonaustin** [therabble/sustain-care.org#1]
`Issue ID:    001
    Issue Name:    Dedicated Domain for Sustain Care Project
    Description:    We need a dedicated domain at dnsimple with SSL support mapped to basic hosting services.
    Tags:    infrastructure
`

was in issues doc on google: https://docs.google.com/document/d/1h9k5oVXKIwElhNLgJhI4uWFOQJjJraaZnlINaiz-n4A/edit#heading=h.2fwzybnibav

**Comment by ramlyed** [comment]
@prestonaustin established the domain under Rabble's dmsimple.com account, and he and he has administrative rights to its zone file there to create and update records
