### ISSUE TITLE
Supply Thank You Page

### ISSUE THREAD

**Issue by prestonaustin** [therabble/sustain-care.org#10]
`
    Issue ID:    010
    Issue Name:    Supply Thank You Page
    Description:    Thank you page for users of the meal supply form to land on after filling it out
    Tags:    promotion, supply

`

https://docs.google.com/document/d/1h9k5oVXKIwElhNLgJhI4uWFOQJjJraaZnlINaiz-n4A/edit#heading=h.frex9ylgs837

**Comment by ramlyed** [comment]
Migrating comments for reference:

Edmond Ramly
10:34 PM Apr 6
+edmondramly@gmail.com

Edmond Ramly
12:48 PM Apr 15
Depends on Issue 006 https://drive.google.com/drive/folders/16gtvspp4mosVmSvhPr9yOer4PCG7A7JV, in progress by +matta.claudia@gmail.com +dldaniel@wisc.edu

Edmond Ramly
12:48 PM Apr 15
+matta.claudia@gmail.com
Reassigned to Claudia Matta

**Comment by cmatta2** [comment]
https://docs.google.com/document/d/1JysJ2qalCzfsETdZHiQQph4zt2xoHtctShSu7JT4tjM/edit

This is the link to the drafted Thank you, it is a very brief one. Let me know if I need to reopen.
