### ISSUE TITLE
Project Donation Form

### ISSUE THREAD

**Issue by prestonaustin** [therabble/sustain-care.org#11]
`
    Issue ID:    011
    Issue Name:    Project Donation Form
    Description:    A form where people who are interested in donating support for the project itself can give us information
    Tags:    funding, fiscal

`

https://docs.google.com/document/d/1h9k5oVXKIwElhNLgJhI4uWFOQJjJraaZnlINaiz-n4A/edit#heading=h.88lj42isn871

**Comment by ramlyed** [comment]
Migrating comments for reference:

Edmond Ramly
10:08 PM Apr 6
+matt.feifarek@gmail.com +preston.h.austin@gmail.com
Assigned to Matt Feifarek

Preston Austin
1:03 PM Apr 15
I think +preston.h.austin@gmail.com should take this into the sustain-care page that embeds the payment capacity Matt sets up at Foodworks (item 18: https://docs.google.com/document/d/1h9k5oVXKIwElhNLgJhI4uWFOQJjJraaZnlINaiz-n4A/edit#heading=h.88lj42isn871)

Reassigned to Preston Austin
