### ISSUE TITLE
Project Email Address

### ISSUE THREAD

**Issue by prestonaustin** [therabble/sustain-care.org#12]
`
    Issue ID:    012
    Issue Name:    Project Email Address
    Description:    An email address entirely dedicated to the project that is not the email of any individual, and that can if needed get back into a help desk system if the volume of incoming email increases over time and it becomes problematic to handle it as simple email 
    Tags:    operations, documentation

`

https://docs.google.com/document/d/1h9k5oVXKIwElhNLgJhI4uWFOQJjJraaZnlINaiz-n4A/edit#heading=h.hyvxqww5nt5r

**Comment by mfeif** [comment]
I can set this up; I do this for lots of things. I'd likely do a "sustaincare.madison@gmail.com" and use filters/labels to route and re-route to people. We can futher have @sustain-care.org aliases for "info@" and so on that can get auto-tagged and auto-forwarded as necessary.

I do this for FoodWorks, I set this up for Starting Block, Slow Food, several other things. I can easily tackle this if you want to assign it to me.

**Comment by ramlyed** [comment]
Already done @mfeif . See Google Doc comments

**Comment by mfeif** [comment]
Hmm. I'm getting confused in the carry-over then. If this is done why did we open a new issue? Should I wait a while for things to settle before I start looking at these?

**Comment by ramlyed** [comment]
Yes, I think Preston's intent was to migrate the full record here and we're still migrating some of the statuses
