### ISSUE TITLE
Compile Official Guidance on COVID Food Service Safety

### ISSUE THREAD

**Issue by prestonaustin** [therabble/sustain-care.org#16]
`
    Issue ID:    016
    Issue Name:    Compile Official Guidance on COVID Food Service Safety
    Description:    Compile official guidance on food service safety precautions related to COVID-19
    Tags:    supply, safety

`

https://docs.google.com/document/d/1h9k5oVXKIwElhNLgJhI4uWFOQJjJraaZnlINaiz-n4A/edit#heading=h.4tagp39kpfrw

**Comment by cmatta2** [comment]
Compiled
