### ISSUE TITLE
Identify Food Worker Concerns Not Addressed by Safety Guidance

### ISSUE THREAD

**Issue by prestonaustin** [therabble/sustain-care.org#17]
`
    Issue ID:    017
    Issue Name:    Identify Food Worker Concerns Not Addressed by Safety Guidance
    Description:    Identify food worker concerns not addressed by safety guidance
    Tags:    supply, safety

`

https://docs.google.com/document/d/1h9k5oVXKIwElhNLgJhI4uWFOQJjJraaZnlINaiz-n4A/edit#heading=h.ql6hgu8zer1u

**Comment by mfeif** [comment]
@jchuran Can you give a look-see at http://mattfeifarek.com:8001/safety/ and see if we're getting somewhere?

**Comment by jchuran** [comment]
@mfeif  I like it. I am a little hesitant of using the serious eats article because it doesn't feel official and is not from a regulatory source.

**Comment by mfeif** [comment]
@jchuran Do you think we should take it off, declare it as "iffy", or just let people make their own determination of that as they view?
