### ISSUE TITLE
Sponsor landing page over at foodworks /sustain-care/ slug

### ISSUE THREAD

**Issue by prestonaustin** [therabble/sustain-care.org#18]
`
    Issue ID:    018
    Issue Name:    Sponsor landing page over at foodworks /sustain-care/ slug
    Description:    Use this embed code and write up a quick page that we can use as an "all-purposes" place to send people donating money to support the project itself, the food deliveries, or other aspects of this <form id="paypal" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
                   <input type="hidden" name="cmd" value="_s-xclick">
                   <input type="hidden" name="hosted_button_id" value="NPSREP7KUZG6W">
                   <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" name="submit" alt="PayPal - The safer, easier way to pay online!" border="0">
                   <img alt="" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1" border="0"></form>
    Tags:    funding, fiscal, infrastructure

`

https://docs.google.com/document/d/1h9k5oVXKIwElhNLgJhI4uWFOQJjJraaZnlINaiz-n4A/edit#heading=h.oqxtigd5v53y

**Comment by mfeif** [comment]
Don't need a landing page the /donate/ url works!
