### ISSUE TITLE
Payment Interface

### ISSUE THREAD

**Issue by prestonaustin** [therabble/sustain-care.org#2]
```

    Issue ID:    002
    Issue Name:    Payment interface
    Description:    We need a payment interface that routes money with attached information into FoodWorks
    Tags:    infrastructure, fiscal, funding


```

https://docs.google.com/document/d/1h9k5oVXKIwElhNLgJhI4uWFOQJjJraaZnlINaiz-n4A/edit#heading=h.jvm988spo7ng

**Comment by ramlyed** [comment]
Edmond Ramly 10:03 PM Apr 6
Payment interface
+matt.feifarek@gmail.com
Assigned to Matt Feifarek

Matt Feifarek
Can currently accept paypal. Venmo not possible without another mobile phone number (they're too smart for my voice-mail only phone number).

Looking into a wider platform for other kinds of payment accepting.

4:48 PM Apr 7
Matt Feifarek Marked as done
