### ISSUE TITLE
Web page template(s)

### ISSUE THREAD

**Issue by mfeif** [therabble/sustain-care.org#24]
Make responsive, standards-oriented simple html files that we can dump @prestonaustin's work into as the API and text content comes together.

I can document the tools and build process(es) as necessary. I'll use the *same* template for the take-money landing page on the FoodWorks domain.

**Comment by mfeif** [comment]
Note here for myself: include easy links for viewers to "socially prove" that this is real. Links to EIN, tax-id status, etc.

**Comment by mfeif** [comment]
Update: have reasonably complete templates and build process now. I'll be documenting it before I close this issue.

**Comment by cmatta2** [comment]
@DonG-D-MSN  updated the About Page template

**Comment by cmatta2** [comment]
@mfeif 
Would it help if we add the templates for the "About Us", "What comes next" and "Contact us" **here?**
or Create separate issues for them (just did)?

**Comment by mfeif** [comment]
I think the content/writing is sufficiently distinct from this one, which is about tech and software, so I think you made the right call. Thanks!

**Comment by mfeif** [comment]
Just for the record, site is now live at https://sustain-care.org/ and the repo has all my current working code.

Still need to document the contribution / build process some.

**Comment by mfeif** [comment]
Marking this as complete, as we have the templates made and working.

I will make a new issue for documenting the build process, as that won't hold up launch.
