### ISSUE TITLE
Reach out to new DATCP person 

### ISSUE THREAD

**Issue by ramlyed** [therabble/sustain-care.org#25]
Find out opportunities for collaboration

**Comment by ramlyed** [comment]
Assign to Don and/or Will when on GitHub

**Comment by mfeif** [comment]
Here is more info about DATCP: https://datcp.wi.gov/Pages/Homepage.aspx

**Comment by ramlyed** [comment]
@cmatta2 will coordinate for now

**Comment by cmatta2** [comment]
Assigned to @wrolson22  and @DonG-D-MSN

**Comment by wrolson22** [comment]
I have connected April and Don. I am not sure if they have connected via the phone yet.

**Comment by DonG-D-MSN** [comment]
I e-mailed April Yancer <april.yancer@wisconsin.gov> (works for DATCP and is the Farm to Institution and Wisconsin Food Specialist) on April 23rd. I have received no response. I opened a new issue - Outreach and moved April's name there for future follow-up.
