### ISSUE TITLE
Meal Demand Form

### ISSUE THREAD

**Issue by prestonaustin** [therabble/sustain-care.org#3]
`
    Issue ID:    003
    Issue Name:    Meal Demand Form
    Description:    We need a meal demand form at which potential demand can be resolved into a clearly defined row in a spreadsheet whose columns are the information we would need to reach back out and coordinate specific meal orders
    Tags:    infrastructure, demand

`
https://docs.google.com/document/d/1h9k5oVXKIwElhNLgJhI4uWFOQJjJraaZnlINaiz-n4A/edit#heading=h.tlbumue4hd5x

**Comment by ramlyed** [comment]
for technical implementation
Reassigned to Preston Austin

**Comment by prestonaustin** [comment]
Closing pending future clarification of what we are asking of what suppliers, based on registered projects.
