### ISSUE TITLE
Adding an initiative currently requires a Google Account

### ISSUE THREAD

**Issue by mfeif** [therabble/sustain-care.org#39]
This might discourage people.

There might be a good reason for it. I'm assigning this to Preston to get his input.

**Comment by prestonaustin** [comment]
We can't accept images without this, so it's the simplest option. I agree its an arbitrary filter and ideally I wouldn't require an account, just an email that looks like an email.

**Comment by mfeif** [comment]
It *DOES* require an account, not an email that looks like an email.

If you [open the link](https://docs.google.com/forms/d/e/1FAIpQLScxHg2gCziN-8D1IM3Uz8Q26twcyTwLExwDqvuy71VYjT5MNw/viewform?usp=sf_link) without a logged-in google account (say a private window) you'll see.

**Comment by prestonaustin** [comment]
Yes, it does precisely what I said it does for the reason I stated.

I've removed the file uploads from the form, and changed the email address request to a plain item not a google managed email request. It's now pretty limited in what it offers, but it meets the new requirement you've created of not requiring a login with google and minimized the contact with google to the form itself.

The prior functionality exists on the snapshot version I created, so to revert this change, simply delete the primary sheet, copy the snapshot, rename the copy, and link it to the responses.

https://drive.google.com/drive/folders/1O3DcBs5TyQY24bZ9dy-Qf0ACHO5xciHz

**Comment by mfeif** [comment]
I think we got our wires crossed there. I wasn't adding a requirement, I was asking a question. You've used this stack before to do this exact thing, I was asking for your advice/recommendation.

I also labeled this "won't fix" and closed the issue.

We will need images; I'm reverting to your prior version and following your instructions to do so.
