### ISSUE TITLE
Meal Supply Form

### ISSUE THREAD

**Issue by prestonaustin** [therabble/sustain-care.org#4]
`
    Issue ID:    004
    Issue Name:    Meal Supply Form
    Description:    We need a meal supply form at which potential supply can be resolved into a clearly defined row in a spreadsheet whose columns are the information we would need to reach back out and coordinate specific meal orders
    Tags:    infrastructure, supply

`

https://docs.google.com/document/d/1h9k5oVXKIwElhNLgJhI4uWFOQJjJraaZnlINaiz-n4A/edit#heading=h.hzbt056mw1x

**Comment by ramlyed** [comment]
for technical implementation
Reassigned to Preston Austin

**Comment by prestonaustin** [comment]
Closing pending future clarification of what we are asking of what suppliers, based on registered projects.
