### ISSUE TITLE
Outreach

### ISSUE THREAD

**Issue by DonG-D-MSN** [therabble/sustain-care.org#41]
Outreach about Sustain Care (running list):

- April Yancer <april.yancer@wisconsin.gov> - works for DATCP and is the Farm to Institution and Wisconsin Food Specialist
- e-mailed 4/23/20 - no reply

- Lisa Loup <LLoup@foodfightinc.com> 
- e-mailed 4/13 and 4/16/20 -  no reply

**Comment by ramlyed** [comment]
#test header MD
## test subheader MD
