### ISSUE TITLE
Reach out to Morris Ramen -led initiative

### ISSUE THREAD

**Issue by ramlyed** [therabble/sustain-care.org#45]

**Comment by mfeif** [comment]
The data is in. It has a number of issues, including some typos and has revealed a couple of user-flow issues in the form. I'll convo with @prestonaustin about those latter.

I think that it will be ok to just edit the data in the spreadsheet, but again, I need to check with @prestonaustin 

FWIW, Francesca said that using the site/form was easy, and she had no problems.

**Comment by mfeif** [comment]
I edited the data in the sheet, and nothing blew up.

The description could use a little jazzing up, but it's up, and it's fine for now. Closing.
