### ISSUE TITLE
Reach out to REAP led initiative

### ISSUE THREAD

**Issue by ramlyed** [therabble/sustain-care.org#46]

**Comment by mfeif** [comment]
http://reapfoodgroup.org/farms-to-families/

**Comment by mfeif** [comment]
Sent an email to Mariela, who I met years ago in my Slow Food work.

**Comment by mfeif** [comment]
Am trying a different vector; via Helen, the ED of REAP. Sent a message today.

**Comment by mfeif** [comment]
Their data is in. It looks good; closing this
