### ISSUE TITLE
Logo for Sustain Care Project

### ISSUE THREAD

**Issue by prestonaustin** [therabble/sustain-care.org#5]
`
    Issue ID:    005
    Issue Name:    Logo for Sustain Care Project
    Description:    A logo more fully resolved than the one on slack for use on web pages and in emails
    Tags:    promotion

`
https://docs.google.com/document/d/1h9k5oVXKIwElhNLgJhI4uWFOQJjJraaZnlINaiz-n4A/edit#heading=h.cq0jrhq5w3as

**Comment by mfeif** [comment]
Is this "wontfix" because we're going logo-less, or...?

**Comment by ramlyed** [comment]
I don't know @mfeif. @prestonaustin what was your intent?

**Comment by ramlyed** [comment]
Migrating the comments on this for reference:

Matt Feifarek
11:28 AM Apr 7
Edmond, your friend Dan was posting on Facebook that he was offering design work for people who were working on covid stuff. Maybe hit him up? I can supply him with FWmsn stuff if we want to tie them together. (I don't need that to be the case)

Tomorrow I'll run with the Doctacolar logo I created until we have something new, and just derive things from it. Then a designer can come in and replace assets or redo whole designs with the design brief being "This content, with more design goodness"

Edmond Ramly
12:44 PM Apr 15
pending website mock-up

Edmond Ramly
12:46 PM Apr 15
+preston.h.austin@gmail.com will do or reassign then

**Comment by mfeif** [comment]
I'll close this for now. I think it's in the "would be nice" category, but shouldn't hold up launch of the site or our outreach.

I'm sure we'll think of it again after we're running a bit.
