### ISSUE TITLE
Approve "Contact Us" page 

### ISSUE THREAD

**Issue by ramlyed** [therabble/sustain-care.org#51]

**Comment by wrolson22** [comment]
Don, this can be found on the SC google drive in "SC - Website Pages" titled "Contact Page:..."

I just need your approval since you will be the one to be contacted. I tired to be semi-specific on what to contact about but at first, I'm guessing we will get many general inquiries. 

Let me know if you have questions. Thanks!

**Comment by mfeif** [comment]
I know this is vague, but I'd like to see "more". We'll have alot of people who may want to get in touch who might need a bit of hand-holding. Perhaps we can have a slightly fleshed-out version of the [copy on the home page](https://sustain-care.org/)? (clipped below, would need to be edited for appropriateness):

> Want to help but don’t want to choose? Great! FoodWorks Madison can accept your 501(c)(3) tax-deductible donation and direct it to projects in need. Learn more about how to donate here.
> Have we missed a care initiative? Please tell us about it.
> Do you or people you know need meals? Great! Please tell us about it.
> Want to send a tip to a service worker? Great! You can choose from thousands of workers over here. Want to donate and have us to choose for you? Great! You can donate here and we will send 100% of your donation to a server.
> Want to donate in a large amount or prefer not to donate online? Great! Connect with us here
> Want to help in another way? Can you help deliver meals? Have some produce that you want turned into meals? Have a closed restaurant or other licensed kitchen, and want to help? Can you help in a coordinator role? Something else? Great! Contact us and let us know what you have in mind.

**Comment by DonG-D-MSN** [comment]
See what you think, Matt: [https://docs.google.com/document/d/1zy4A6vf018MOj_qqsG5DzasKxtVt2w6MPa6UM4Yhup8/edit#](url)
