### ISSUE TITLE
Add "press coverage" links to initiative capture form

### ISSUE THREAD

**Issue by mfeif** [therabble/sustain-care.org#53]
Reading about what one of our likely "model initiatives" (see #50) in the [news today](https://isthmus.com/food-drink/noodles-anew/), it occurred to me that other initiatives/projects might like to refer potential donors to their good press; it would perhaps be easier for them to "show" what they've been doing than to write up copy to "tell" us about it. Or both, of course.

Can we have a form capture element be added to grab these? I suppose it could be just like the social urls, but these links might get long and nasty, so maybe there is a better way.

Assigning to @cmatta2 for project management, and @prestonaustin for formsy stuff and general input from his experience.

**Comment by prestonaustin** [comment]
I'm thinking this form is too long, and we should instead use google alerts ourselves to discover coverage, and follow up with contacts in a secondary process to solicit information about coverage. I see why we want it but I don't think we should change this form to gather it at this time, until we have good proof via tests we are on the right track with it as is.

In a technical sense, Matt, I don't think there is a clever way to do this. We would probably want to create a 4 item form where we sent project's a pre-filled form link that selected them in a pulldown in item one (so we can pair up incoming data with a clean key) and then requested a news URL, a short title in their words for that news link (under 80 characters), a short description in their words of that piece of news (under 150 characters), and ideally but optionally an image representing that piece of news suitable for social media and newsletter shares.

This makes of the news an object with properties we can flexibly use, and evaluate from a list context (which links alone make difficult or impossible depending on where they go)

Provisionally closing this item. If we must have this form now, I suggest opening a new item with the spec above or something similar, to do a separate form for this.
