### ISSUE TITLE
Text for Project Landing Page

### ISSUE THREAD

**Issue by prestonaustin** [therabble/sustain-care.org#6]
`
    Issue ID:    006
    Issue Name:    Text for Project Landing Page
    Description:    Text for a landing page describing the project itself in its goals, including answers to questions about what the scope this is, what it is not, links to related things that people might care about, reasons why we should be trusted, organizational affiliations that matter, and the names and contact means for key people
    Tags:    promotion, infrastructure

`

https://docs.google.com/document/d/1h9k5oVXKIwElhNLgJhI4uWFOQJjJraaZnlINaiz-n4A/edit#heading=h.ep11odetpuxq

**Comment by ramlyed** [comment]
Migrating comments for reference:

Edmond Ramly
10:32 PM Apr 6
+edmondramly@gmail.com
Assigned to you

Edmond Ramly
2:33 PM Apr 8
Drafted some mission language for discussion and consensus at today's meeting, in the Sustain Care - What & Why document

Preston Austin
12:43 PM Apr 15
In progress by +matta.claudia@gmail.com and +dldaniel@wisc.edu in SC - Website Pages

**Comment by ramlyed** [comment]
@mfeif  is going to bring the whole website closer to concrete so we can all react

**Comment by cmatta2** [comment]
Completed with @DonG-D-MSN
