### ISSUE TITLE
Text for Top of Meal Demand Form

### ISSUE THREAD

**Issue by prestonaustin** [therabble/sustain-care.org#7]
`
    Issue ID:    007
    Issue Name:    Text for Top of Meal Demand Form
    Description:    Text for the top of the meal demand registration form explaining who it is form and what alternatives exist if they are not for you
    Tags:    infrastructure, demand

`

https://docs.google.com/document/d/1h9k5oVXKIwElhNLgJhI4uWFOQJjJraaZnlINaiz-n4A/edit#heading=h.gvqfnocpfemf

**Comment by ramlyed** [comment]
Migrating comments for reference:

Edmond Ramly
10:33 PM Apr 6
+edmondramly@gmail.com

Preston Austin
12:47 PM Apr 15
Depends on Issue 006 https://drive.google.com/drive/folders/16gtvspp4mosVmSvhPr9yOer4PCG7A7JV, in progress by +matta.claudia@gmail.com +dldaniel@wisc.edu

**Comment by cmatta2** [comment]
Drafted and delivered to website team
