### ISSUE TITLE
Text for Top of Meal Supply Form

### ISSUE THREAD

**Issue by prestonaustin** [therabble/sustain-care.org#8]
`
    Issue ID:    008
    Issue Name:    Text for Top of Meal Supply Form
    Description:    Text for the top of the meal supply registration form explaining who it is form and what alternatives exist if they are not for you
    Tags:    infrastructure, supply

`

https://docs.google.com/document/d/1h9k5oVXKIwElhNLgJhI4uWFOQJjJraaZnlINaiz-n4A/edit#heading=h.frex9ylgs837

**Comment by ramlyed** [comment]
Migrating comments for reference:

Edmond Ramly
10:35 PM Apr 6
+edmondramly@gmail.com

Edmond Ramly
12:48 PM Apr 15
Depends on Issue 006 https://drive.google.com/drive/folders/16gtvspp4mosVmSvhPr9yOer4PCG7A7JV, in progress by +matta.claudia@gmail.com +dldaniel@wisc.edu
Reassigned to Claudia Matta

**Comment by cmatta2** [comment]
Done.
