### ISSUE TITLE
Demand Thank You Page

### ISSUE THREAD

**Issue by prestonaustin** [therabble/sustain-care.org#9]
`
    Issue ID:    009
    Issue Name:    Demand Thank You Page
    Description:    Thank you page for users of the meal demand form to land on after filling it out
    Tags:    promotion, demand

`
https://docs.google.com/document/d/1h9k5oVXKIwElhNLgJhI4uWFOQJjJraaZnlINaiz-n4A/edit#heading=h.w65ga14m1cgz

**Comment by ramlyed** [comment]
Migrating comments for reference:

Edmond Ramly
10:34 PM Apr 6
+edmondramly@gmail.com

Preston Austin
12:48 PM Apr 15
Depends on Issue 006 https://drive.google.com/drive/folders/16gtvspp4mosVmSvhPr9yOer4PCG7A7JV, in progress by +matta.claudia@gmail.com +dldaniel@wisc.edu
Reassigned to Claudia Matta

**Comment by cmatta2** [comment]
Created a template here if this is what we need. 

https://docs.google.com/document/d/1JysJ2qalCzfsETdZHiQQph4zt2xoHtctShSu7JT4tjM/edit
